version: 0.1

phases:
  install:
      commands:
        - echo $AWS_DEFAULT_REGION
        - echo $AWS_REGION
        - echo $CODEBUILD_BUILD_ARN
        - echo $CODEBUILD_BUILD_ID
        - echo $CODEBUILD_BUILD_IMAGE
        - echo $CODEBUILD_BUILD_SUCCEEDING
        - echo $CODEBUILD_INITIATOR
        - echo $CODEBUILD_KMS_KEY_ID
        - echo $CODEBUILD_LOG_PATH
        - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
        - echo $CODEBUILD_SOURCE_REPO_URL
        - echo $CODEBUILD_SOURCE_VERSION
        - echo $CODEBUILD_SRC_DIR
        - echo $CODEBUILD_START_TIME
        - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
        - echo $CODEBUILD_WEBHOOK_BASE_REF
        - echo $CODEBUILD_WEBHOOK_EVENT
        - echo $CODEBUILD_WEBHOOK_HEAD_REF
        - echo $CODEBUILD_WEBHOOK_TRIGGER
        - echo $HOME
  build:
    commands:
        - git status
        - printf [{\"name\":\"$NODE_ENV-backend\",\"imageUri\":\"%s\"}] $IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
